version: "2.0"

services:
  cobalton:
    # container_name: cobalton
    # image: cobalton
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - COBALTON_VERSION=${COBALTON_VERSION}
        - COBALTON_OPTS=${COBALTON_OPTS}
        - JAVA_OPTS=${JAVA_OPTS}
    volumes:
      - /var/bots/james:/var/bots/james
