version: "2.0"

services:
    cobalton:
        image: cobalton:latest
        container_name: cobalton
        restart: on-failure
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - COBALTON_OPTS=${COBALTON_OPTS}
                - JAVA_OPTS=${JAVA_OPTS}
        volumes:
            - /var/bots/Cobalton:/data
