version: "2.0"

services:
    Cobalton:
        image: Cobalton:latest
        container_name: Cobalton
        restart: on-failure
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - APP_VERSION=${APP_VERSION}
                - COBALTON_OPTS=${COBALTON_OPTS}
                - JAVA_OPTS=${JAVA_OPTS}
        volumes:
            - /var/bots/Cobalton:/data
