version: "2.0"

services:
    cobalton:
        image: cobalton:latest
        container_name: cobalton
        restart: on-failure
        working_dir: /
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./build/install/Cobalton:/exec:ro
            - /var/bots/Cobalton:/data
        entrypoint: /exec/bin/Cobalton
