FROM adoptopenjdk/openjdk11:alpine

ARG JAVA_OPTS
ENV JAVA_OPTS=$JAVA_OPTS
ARG COBALTON_OPTS
ENV COBALTON_OPTS=$COBALTON_OPTS
ARG COBALTON_VERSION
ENV COBALTON_VERSION=$COBALTON_VERSION

COPY build/install/Cobalton /opt/bots/Cobalton

ENTRYPOINT exec /opt/bots/Cobalton/bin/Cobalton JAVA_OPTS=$JAVA_OPTS COBALTON_OPTS=$COBALTON_OPTS
