version: "2.0"

services:
  cobalton:
    container_name: Cobalton
    image: cobalton:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - COBALTON_VERSION=${COBALTON_VERSION}
        - COBALTON_OPTS=${COBALTON_OPTS}
        - JAVA_OPTS=${JAVA_OPTS}
    volumes:
      - /data:/var/bots/james
