version: "2.0"

services:
    cobalton:
        image: cobalton:public
        container_name: cobalton-public
        restart: on-failure
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - /var/bots/Cobalton:/app/data:rw
        working_dir: /app
        entrypoint: /app/binaries/bin/Cobalton
