version: "2.0"

services:
    cobalton:
        image: cobalton:latest
        container_name: cobalton
        restart: on-failure
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./docker:/app:ro
            - /var/bots/Cobalton:/app:rw
        working_dir: /app
        entrypoint: /app/bin/Cobalton
